#  The MIT License (MIT)
#
#  Copyright (c) 2022 Joshua Glass (SuperNinja_4965)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#

name: Compile and CodeQL

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
    env:
      PICO_SDK_PATH: ${GITHUB_WORKSPACE}/pico/pico-sdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Dependencies 
      - name: Install Dependencies 
        run: |
          sudo apt update
          sudo apt install git cmake gcc-arm-none-eabi gcc g++ gdb-multiarch automake autoconf build-essential texinfo libtool libftdi-dev libusb-1.0-0-dev minicom openocd
          
      # Get the core count so we can use more than one core for compile
      - name: Get core count
        id: core_count
        run : cat /proc/cpuinfo  | grep processor | wc -l

      # Setup the SDK
      - name: Setup the SDK
        run: |
          mkdir ${GITHUB_WORKSPACE}/pico/
          git -C ${GITHUB_WORKSPACE}/pico/ clone https://github.com/raspberrypi/pico-sdk.git
          git -C ${GITHUB_WORKSPACE}/pico/pico-sdk submodule update --init --recursive
          
      # Run the SDK tests - Helps ensure the SDK and our environemnt is good.
      - name: Run SDK Test runs
        run: |
          mkdir ${GITHUB_WORKSPACE}/pico/pico-sdk/build
          cmake -S ${GITHUB_WORKSPACE}/pico/pico-sdk -B ${GITHUB_WORKSPACE}/pico/pico-sdk/build
          make -C ${GITHUB_WORKSPACE}/pico/pico-sdk/build -j ${{steps.core_count.outputs.output}}

      # Clone Pimorini's Librarys needed for the code
      - name: Clone Pimoroni libraries
        run: |
          git clone https://github.com/pimoroni/pimoroni-pico.git ${GITHUB_WORKSPACE}/libs/pimoroni-pico
          git -C ${GITHUB_WORKSPACE}/libs/pimoroni-pico submodule update --init --recursive
          
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          
      # Builds the code
      - name: Build the Code
        run: |  
          mkdir build
          cd build
          cmake ..
          make -j ${{steps.core_count.outputs.output}}
          
      # Upload the artifact
      - uses: actions/upload-artifact@v2
        with:
          name: UF2-Compiled-Binary.uf2
          path: ${GITHUB_WORKSPACE}/build/examples/Simple/SimpleExample.uf2
          retention-days: 60
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
